package ir.irautox.clashofdrayven;

import android.content.Context;
import android.graphics.*;
import android.view.MotionEvent;
import android.view.View;
import org.json.*;
import java.util.*;

final class BattleView extends View {
    interface Listener{void finishBattle(int gold,int elixir,int stars,int destruction);}
    private static final long DURATION_MS=120000L;private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);
    private final PackManager packs;private final GameModel model;private final Listener listener;private final String playerName;private final ArrayList<Enemy>enemies=new ArrayList<>();private final ArrayList<Fighter>fighters=new ArrayList<>();private final ArrayList<Card>cards=new ArrayList<>();private final Typeface dry;
    private String selected;private long started=System.currentTimeMillis(),lastFrame=System.nanoTime();private boolean ended=false,townHallDown=false,rewardApplied=false;private final RectF returnButton=new RectF();private int finalStars,finalDestruction,finalGold,finalElixir;
    BattleView(Context c,GameModel m,PackManager p,String n,Listener l){this(c,m,p,n,null,l);}
    BattleView(Context context,GameModel model,PackManager packs,String playerName,JSONObject match,Listener listener){super(context);this.model=model;this.packs=packs;this.playerName=playerName==null?"فرمانده":playerName;this.listener=listener;this.dry=packs.font();setLayerType(View.LAYER_TYPE_SOFTWARE,null);setLayoutDirection(View.LAYOUT_DIRECTION_RTL);if(!createFromMatch(match))createEnemyBase();setFocusable(true);}
    private boolean createFromMatch(JSONObject match){try{if(match==null)return false;JSONObject defender=match.optJSONObject("defender");JSONObject state=defender==null?null:defender.optJSONObject("state");JSONArray bs=state==null?null:state.optJSONArray("buildings");if(bs==null||bs.length()==0)return false;for(int i=0;i<bs.length()&&i<80;i++){JSONObject b=bs.getJSONObject(i);String id=b.optString("definitionId","townhall");int x=b.optInt("x",9),y=b.optInt("y",9),level=Math.max(1,b.optInt("level",1));float nx=.12f+(x/20f)*.76f,ny=.17f+(y/20f)*.58f;enemies.add(new Enemy(id,nx,ny,level,NativeBridge.enemyHp(id,Math.max(model.level,level))));}return!enemies.isEmpty();}catch(Exception ex){enemies.clear();return false;}}
    private void createEnemyBase(){String[]ids={"townhall","cannon","archertower","goldmine","elixircollector","mortar","goldstorage","elixirstorage","barracks","armycamp","clancastle","airdefense"};float[][]pos={{.50f,.42f},{.29f,.33f},{.70f,.31f},{.37f,.56f},{.64f,.58f},{.50f,.25f},{.22f,.49f},{.78f,.49f},{.41f,.28f},{.59f,.29f},{.50f,.58f},{.76f,.28f}};for(int i=0;i<ids.length;i++)enemies.add(new Enemy(ids[i],pos[i][0],pos[i][1],Math.max(1,model.level/3),NativeBridge.enemyHp(ids[i],model.level)));}
    @Override protected void onDraw(Canvas c){super.onDraw(c);long n=System.nanoTime();float dt=Math.min(.05f,(n-lastFrame)/1_000_000_000f);lastFrame=n;if(!ended)update(dt);int w=getWidth(),h=getHeight();drawField(c,w,h);drawEnemies(c,w,h);drawFighters(c,w,h);drawTop(c,w,h);drawTroopBar(c,w,h);if(ended)drawResult(c,w,h);else postInvalidateOnAnimation();}
    private void update(float dt){if(System.currentTimeMillis()-started>=DURATION_MS){endBattle();return;}for(Fighter f:fighters){if(f.dead)continue;Enemy target=nearestAlive(f.x,f.y);if(target==null){endBattle();return;}float dx=target.x-f.x,dy=target.y-f.y,d=(float)Math.sqrt(dx*dx+dy*dy);GameCatalog.UnitSpec u=GameCatalog.unit(f.id);float range=u==null?.052f:u.range;if(d>range){float speed=u==null?.13f:u.speed,step=speed*dt;f.x+=dx/Math.max(.001f,d)*Math.min(step,d-range);f.y+=dy/Math.max(.001f,d)*Math.min(step,d-range);f.dir=Math.abs(dx)>Math.abs(dy)?(dx<0?'l':'r'):(dy<0?'b':'f');}else{f.cooldown-=dt;if(f.cooldown<=0){target.hp-=u==null?18f:u.damage;f.cooldown=u==null?.72f:u.delay;if(target.hp<=0&&!target.dead){target.dead=true;if("townhall".equals(target.id))townHallDown=true;}}}}
        for(Enemy e:enemies){if(e.dead)continue;float[]def=NativeBridge.buildingCombat(e.id,e.level);if(def==null||def.length<3||def[0]<=0)continue;e.cooldown-=dt;if(e.cooldown>0)continue;Fighter victim=nearestFighter(e.x,e.y,def[0]);if(victim!=null){victim.hp-=def[1];e.cooldown=Math.max(.25f,def[2]);if(victim.hp<=0)victim.dead=true;}}
        boolean any=false;for(Fighter f:fighters)if(!f.dead){any=true;break;}if(!fighters.isEmpty()&&!any&&System.currentTimeMillis()-started>8000)endBattle();if(nearestAlive(.5f,.5f)==null)endBattle();}
    private Enemy nearestAlive(float x,float y){Enemy best=null;float bd=Float.MAX_VALUE;for(Enemy e:enemies){if(e.dead)continue;float dx=e.x-x,dy=e.y-y,d=dx*dx+dy*dy;if(d<bd){bd=d;best=e;}}return best;}
    private Fighter nearestFighter(float x,float y,float range){Fighter best=null;float bd=range*range;for(Fighter f:fighters){if(f.dead)continue;float dx=f.x-x,dy=f.y-y,d=dx*dx+dy*dy;if(d<=bd){bd=d;best=f;}}return best;}
    private void drawField(Canvas c,int w,int h){LinearGradient sky=new LinearGradient(0,0,0,h,0xff1c8098,0xff173f35,Shader.TileMode.CLAMP);p.setShader(sky);c.drawRect(0,0,w,h,p);p.setShader(null);RectF field=new RectF(w*.04f,h*.12f,w*.96f,h*.82f);p.setColor(0xff66a953);c.drawRoundRect(field,36,36,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(0x33552f1e);for(int i=1;i<18;i++){float x=field.left+field.width()*i/18f;c.drawLine(x,field.top,x,field.bottom,p);}for(int i=1;i<11;i++){float y=field.top+field.height()*i/11f;c.drawLine(field.left,y,field.right,y,p);}p.setStyle(Paint.Style.FILL);}
    private void drawEnemies(Canvas c,int w,int h){for(Enemy e:enemies){float sx=e.x*w,sy=e.y*h;if(e.dead){p.setColor(0x66000000);c.drawCircle(sx,sy,28,p);continue;}Bitmap b=packs.building(e.id);p.setColor(0x55000000);c.drawOval(new RectF(sx-43,sy+22,sx+43,sy+39),p);if(b!=null)drawBitmapBottom(c,b,sx,sy+28,92);else{p.setColor(0xff8a6045);c.drawRoundRect(new RectF(sx-30,sy-42,sx+30,sy+28),8,8,p);}float hp=Math.max(0,e.hp/e.maxHp);p.setColor(0xcc1b2024);c.drawRoundRect(new RectF(sx-35,sy-57,sx+35,sy-49),4,4,p);p.setColor(hp>.5f?0xff50d070:(hp>.25f?0xffffc247:0xffff5b52));c.drawRoundRect(new RectF(sx-35,sy-57,sx-35+70*hp,sy-49),4,4,p);}}
    private void drawFighters(Canvas c,int w,int h){long tick=(System.currentTimeMillis()/180)%2;for(Fighter f:fighters){if(f.dead)continue;float sx=f.x*w,sy=f.y*h+(tick==0?-2:2);Bitmap b=packs.unitFrame(f.id,f.dir);p.setColor(0x55000000);c.drawCircle(sx,sy+13,18,p);if(b!=null){p.setFilterBitmap(false);c.drawBitmap(b,null,new RectF(sx-26,sy-40,sx+26,sy+18),p);}else{p.setColor(0xffd9c27a);c.drawCircle(sx,sy-5,16,p);}}}
    private void drawTop(Canvas c,int w,int h){p.setColor(0xe91a2831);c.drawRoundRect(new RectF(18,14,w-18,82),19,19,p);text(c,playerName,42,46,17,Color.WHITE,Paint.Align.LEFT);text(c,"نبرد",42,68,11,0xffa8bbc2,Paint.Align.LEFT);int sec=Math.max(0,(int)((DURATION_MS-(System.currentTimeMillis()-started)+999)/1000));text(c,String.format(Locale.US,"%d:%02d",sec/60,sec%60),w/2f,55,24,Color.WHITE,Paint.Align.CENTER);int destruction=destruction(),stars=NativeBridge.battleStars(destruction,townHallDown);text(c,destruction+"٪",w-210,47,18,Color.WHITE,Paint.Align.LEFT);drawStars(c,w-120,25,stars,26,31);int[]loot=NativeBridge.lootPreview(model.level);text(c,"غنیمت احتمالی "+(loot!=null?loot[0]:0)+" طلا",w-300,70,11,0xffd8e5d9,Paint.Align.LEFT);}
    private void drawStars(Canvas c,float x,float y,int count,float size,float step){for(int i=0;i<3;i++){Bitmap star=packs.ui("star");RectF r=new RectF(x+i*step,y,x+i*step+size,y+size);if(star!=null){p.setAlpha(i<count?255:55);c.drawBitmap(star,null,r,p);p.setAlpha(255);}else text(c,i<count?"★":"☆",r.centerX(),r.bottom,20,i<count?0xffffcf45:0xff71818a,Paint.Align.CENTER);}}
    private void drawTroopBar(Canvas c,int w,int h){cards.clear();p.setColor(0xf2162229);c.drawRect(0,h*.82f,w,h,p);int available=0;for(GameCatalog.UnitSpec u:GameCatalog.UNITS)if(model.units.getOrDefault(u.id,0)>0)available++;if(available==0){text(c,"نیرویی برای اعزام باقی نمانده",w/2f,h*.91f,17,0xffd7e0e4,Paint.Align.CENTER);return;}float gap=10,cardW=Math.min(112f,(w-40-gap*(available-1))/available),total=available*cardW+(available-1)*gap,x=(w-total)/2f,y=h*.835f,cardH=h*.145f;for(GameCatalog.UnitSpec u:GameCatalog.UNITS){int count=model.units.getOrDefault(u.id,0);if(count<=0)continue;RectF r=new RectF(x,y,x+cardW,y+cardH);cards.add(new Card(u.id,r));boolean sel=u.id.equals(selected);p.setColor(sel?0xfff0b934:0xff384a54);c.drawRoundRect(r,14,14,p);Bitmap b=packs.unit(u.id);if(b!=null)c.drawBitmap(b,null,new RectF(r.left+8,r.top+7,r.left+cardW*.63f,r.bottom-8),p);text(c,"×"+count,r.right-10,r.top+25,13,Color.WHITE,Paint.Align.RIGHT);text(c,u.name,r.centerX(),r.bottom-10,10,Color.WHITE,Paint.Align.CENTER);x+=cardW+gap;}}
    private int destruction(){int dead=0;for(Enemy e:enemies)if(e.dead)dead++;return Math.round(dead*100f/enemies.size());}
    private void endBattle(){if(ended)return;ended=true;finalDestruction=destruction();finalStars=NativeBridge.battleStars(finalDestruction,townHallDown);int[]reward=NativeBridge.battleReward(model.level,finalDestruction,finalStars);finalGold=reward!=null&&reward.length>0?Math.max(0,reward[0]):0;finalElixir=reward!=null&&reward.length>1?Math.max(0,reward[1]):0;rewardApplied=true;invalidate();}
    private void drawResult(Canvas c,int w,int h){p.setColor(0xcc071014);c.drawRect(0,0,w,h,p);RectF panel=new RectF(w*.23f,h*.18f,w*.77f,h*.76f);p.setColor(0xff253740);c.drawRoundRect(panel,30,30,p);text(c,finalStars>=1?"پیروزی":"نبرد تمام شد",w/2f,h*.29f,30,Color.WHITE,Paint.Align.CENTER);drawStars(c,w/2f-55,h*.34f,finalStars,34,38);text(c,finalDestruction+"٪ تخریب",w/2f,h*.49f,20,Color.WHITE,Paint.Align.CENTER);text(c,"نتیجه برای تایید به سرور ارسال می‌شود",w/2f,h*.57f,14,0xffe6f0e4,Paint.Align.CENTER);returnButton.set(w*.38f,h*.63f,w*.62f,h*.71f);p.setColor(0xffd9952c);c.drawRoundRect(returnButton,16,16,p);text(c,"بازگشت",returnButton.centerX(),returnButton.centerY()+6,15,Color.WHITE,Paint.Align.CENTER);}
    @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_DOWN)return true;float x=e.getX(),y=e.getY();if(ended){if(returnButton.contains(x,y)&&rewardApplied){rewardApplied=false;listener.finishBattle(finalGold,finalElixir,finalStars,finalDestruction);}return true;}for(Card card:cards)if(card.rect.contains(x,y)){selected=selected!=null&&selected.equals(card.id)?null:card.id;invalidate();return true;}if(y<getHeight()*.12f||y>getHeight()*.82f||selected==null)return true;int count=model.units.getOrDefault(selected,0);if(count<=0){selected=null;return true;}float nx=Math.max(.07f,Math.min(.93f,x/getWidth())),ny=Math.max(.14f,Math.min(.78f,y/getHeight()));fighters.add(new Fighter(selected,nx,ny));model.units.put(selected,count-1);if(count-1<=0)selected=null;invalidate();return true;}
    private void drawBitmapBottom(Canvas c,Bitmap b,float cx,float bottom,float max){float scale=Math.min(max/Math.max(1,b.getWidth()),max/Math.max(1,b.getHeight()));float ww=b.getWidth()*scale,hh=b.getHeight()*scale;c.drawBitmap(b,null,new RectF(cx-ww/2,bottom-hh,cx+ww/2,bottom),p);}
    private void text(Canvas c,String s,float x,float y,float size,int color,Paint.Align align){p.setShader(null);p.setTypeface(dry);p.setColor(color);p.setTextSize(size);p.setTextAlign(align);c.drawText(s,x,y,p);}
    private static final class Enemy{final String id;final float x,y,maxHp;final int level;float hp,cooldown;boolean dead;Enemy(String id,float x,float y,int level,float hp){this.id=id;this.x=x;this.y=y;this.level=level;this.hp=hp;this.maxHp=hp;}}
    private static final class Fighter{final String id;float x,y,cooldown,hp=150;char dir='f';boolean dead;Fighter(String id,float x,float y){this.id=id;this.x=x;this.y=y;GameCatalog.UnitSpec u=GameCatalog.unit(id);if(u!=null)hp=110+u.power*6;}}
    private static final class Card{final String id;final RectF rect;Card(String id,RectF rect){this.id=id;this.rect=new RectF(rect);}}
}
