package ir.irautox.clashofdrayven;

import android.content.Context;
import android.graphics.*;
import android.view.*;
import java.util.*;

final class GameView extends View {
    interface Listener{void shop();void army();void attack();void clan();void profile();void chat();void placeBuilding(GameCatalog.BuildingSpec s,int x,int y);void upgrade(GameModel.Building b);void dirty(String toast);}
    private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);private final RectF[]nav=new RectF[5];private final RectF chatButton=new RectF();
    private final Listener listener;private final PackManager packs;private final Typeface dry;private final String playerName;private final ScaleGestureDetector scaleDetector;private final GestureDetector gestureDetector;
    private GameModel model;private GameCatalog.BuildingSpec buildMode;private GameModel.Building selectedBuilding;
    private String toast="دهکده آماده است";private long toastUntil=System.currentTimeMillis()+2200;private float tileW=72f,tileH=36f,originX,originY,zoom=1f,panX=0f,panY=0f;
    GameView(Context c,GameModel m,PackManager packs,String playerName,Listener listener){super(c);model=m;this.packs=packs;this.playerName=playerName==null||playerName.trim().isEmpty()?"فرمانده":playerName.trim();this.listener=listener;dry=packs.font();p.setTypeface(dry);setLayerType(View.LAYER_TYPE_SOFTWARE,null);setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
        scaleDetector=new ScaleGestureDetector(c,new ScaleGestureDetector.SimpleOnScaleGestureListener(){@Override public boolean onScale(ScaleGestureDetector d){zoom=Math.max(.62f,Math.min(1.85f,zoom*d.getScaleFactor()));invalidate();return true;}});
        gestureDetector=new GestureDetector(c,new GestureDetector.SimpleOnGestureListener(){@Override public boolean onDown(MotionEvent e){return true;}@Override public boolean onScroll(MotionEvent e1,MotionEvent e2,float dx,float dy){if(scaleDetector.isInProgress())return false;panX=Math.max(-getWidth()*.35f,Math.min(getWidth()*.35f,panX-dx));panY=Math.max(-getHeight()*.22f,Math.min(getHeight()*.22f,panY-dy));invalidate();return true;}@Override public boolean onSingleTapUp(MotionEvent e){return handleTap(e.getX(),e.getY());}});
    }
    void selectBuilding(GameCatalog.BuildingSpec s){buildMode=s;selectedBuilding=null;showToast("برای ساخت "+s.name+" روی زمین بزن");}
    void showToast(String s){toast=s;toastUntil=System.currentTimeMillis()+3200;invalidate();}
    @Override protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();originX=w*.52f;originY=Math.max(115,h*.15f);tileW=Math.max(58,Math.min(82,w/18f));tileH=tileW*.50f;drawBackground(c,w,h);c.save();c.translate(panX,panY);c.scale(zoom,zoom,w*.5f,h*.46f);drawGrid(c);drawBuildings(c);c.restore();drawHud(c,w,h);drawNav(c,w,h);drawChatButton(c,w,h);if(buildMode!=null)drawHint(c,w,"ساخت "+buildMode.name+" • "+buildMode.cost+" "+GameCatalog.currencyName(buildMode.currency));else if(selectedBuilding!=null){int cost=NativeBridge.upgradeCost(selectedBuilding.id,selectedBuilding.level);drawHint(c,w,cost<0?"حداکثر سطح":"ارتقای "+GameCatalog.building(selectedBuilding.id).name+" • "+cost+" طلا");}if(System.currentTimeMillis()<toastUntil)drawToast(c,w,h);}
    private void drawBackground(Canvas c,int w,int h){LinearGradient g=new LinearGradient(0,0,0,h,0xff68b8d2,0xff214d3d,Shader.TileMode.CLAMP);p.setShader(g);c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(0x330b1b20);c.drawCircle(w*.13f,h*.28f,w*.14f,p);c.drawCircle(w*.88f,h*.34f,w*.18f,p);}
    private PointF tile(int x,int y){return new PointF(originX+(x-y)*tileW/2f,originY+(x+y)*tileH/2f);}
    private PointF untransform(float sx,float sy){float cx=getWidth()*.5f,cy=getHeight()*.46f;return new PointF((sx-panX-cx)/zoom+cx,(sy-panY-cy)/zoom+cy);}
    private int[] screen(float sx,float sy){PointF z=untransform(sx,sy);float x=((z.y-originY)/(tileH/2f)+(z.x-originX)/(tileW/2f))/2f;float y=((z.y-originY)/(tileH/2f)-(z.x-originX)/(tileW/2f))/2f;return new int[]{Math.round(x),Math.round(y)};}
    private void drawGrid(Canvas c){for(int sum=0;sum<=38;sum++)for(int x=0;x<20;x++){int y=sum-x;if(y<0||y>=20)continue;PointF q=tile(x,y);Path path=new Path();path.moveTo(q.x,q.y-tileH/2);path.lineTo(q.x+tileW/2,q.y);path.lineTo(q.x,q.y+tileH/2);path.lineTo(q.x-tileW/2,q.y);path.close();p.setColor((x+y)%2==0?0xff67a957:0xff72b25d);p.setStyle(Paint.Style.FILL);c.drawPath(path,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setColor(0x55517242);c.drawPath(path,p);p.setStyle(Paint.Style.FILL);}}
    private void drawBuildings(Canvas c){ArrayList<GameModel.Building>bs=new ArrayList<>(model.buildings);Collections.sort(bs,(a,b)->Integer.compare(a.x+a.y,b.x+b.y));for(GameModel.Building b:bs){PointF q=tile(b.x,b.y);if(b==selectedBuilding){p.setColor(0x99ffd65a);c.drawCircle(q.x,q.y-20,54,p);}p.setColor(0x59000000);c.drawOval(new RectF(q.x-34,q.y-7,q.x+34,q.y+15),p);Bitmap bm=packs.building(b.id);if(bm!=null)drawBitmapBottom(c,bm,q.x,q.y+7,"wall".equals(b.id)?50:94);else{p.setColor(0xff8e6449);c.drawRoundRect(new RectF(q.x-25,q.y-50,q.x+25,q.y),8,8,p);}p.setColor(0xe51c2c34);c.drawRoundRect(new RectF(q.x+17,q.y-66,q.x+54,q.y-43),8,8,p);text(c,"L"+b.level,q.x+35,q.y-49,9,Color.WHITE,Paint.Align.CENTER);}}
    private void drawHud(Canvas c,int w,int h){p.setColor(0xe817262e);c.drawRoundRect(new RectF(18,16,Math.min(350,w*.33f),88),20,20,p);p.setColor(0xff4b9dd8);c.drawCircle(54,52,25,p);text(c,String.valueOf(model.level),54,59,17,Color.WHITE,Paint.Align.CENTER);text(c,playerName,91,45,17,Color.WHITE,Paint.Align.LEFT);text(c,"#"+(model.playerId>0?model.playerId:"OFF")+" • "+model.rank()+" • "+model.points,91,69,9,0xffb8c9ce,Paint.Align.LEFT);float chipW=Math.min(172,w*.145f),gap=10,total=chipW*3+gap*2,start=w-total-20;resource(c,start,"gold",model.gold,0xffffc641,chipW);resource(c,start+chipW+gap,"elixir",model.elixir,0xffda50d5,chipW);resource(c,start+(chipW+gap)*2,"gem",model.gems,0xff35dfa0,chipW);p.setColor(0xaa142229);c.drawRoundRect(new RectF(w*.42f,20,w*.58f,65),15,15,p);text(c,"CLASH OF DRAYVEN",w*.50f,49,15,0xffffd572,Paint.Align.CENTER);}
    private void resource(Canvas c,float x,String key,int value,int color,float width){p.setColor(0xe91b2b33);RectF r=new RectF(x,19,x+width,70);c.drawRoundRect(r,15,15,p);Bitmap bm=packs.ui(key);if(bm!=null)c.drawBitmap(bm,null,new RectF(x+7,25,x+43,61),p);else{p.setColor(color);c.drawCircle(x+25,44,17,p);}text(c,String.format(Locale.US,"%,d",value),x+50,52,14,Color.WHITE,Paint.Align.LEFT);}
    private void drawNav(Canvas c,int w,int h){float barH=Math.max(96,h*.14f);p.setColor(0xf3132028);c.drawRect(0,h-barH,w,h,p);String[]keys={"attack","shop","army","clan","profile"};String[]labels={"حمله","فروشگاه","ارتش","کلن","پروفایل"};float bw=Math.min(148,(w-70)/5f),gap=8,total=bw*5+gap*4,start=(w-total)/2f,top=h-barH+11;for(int i=0;i<5;i++){RectF r=new RectF(start+i*(bw+gap),top,start+i*(bw+gap)+bw,h-14);nav[i]=r;boolean attack=i==0;p.setColor(attack?0xffd77d2c:0xff344852);c.drawRoundRect(r,17,17,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(attack?0xffffb85b:0xff526a74);c.drawRoundRect(r,17,17,p);p.setStyle(Paint.Style.FILL);Bitmap bm=packs.ui(keys[i]);float icon=Math.min(42,r.height()*.48f);if(bm!=null)c.drawBitmap(bm,null,new RectF(r.left+11,r.top+12,r.left+11+icon,r.top+12+icon),p);text(c,labels[i],r.right-11,r.centerY()+5,11,Color.WHITE,Paint.Align.RIGHT);}}
    private void drawChatButton(Canvas c,int w,int h){chatButton.set(12,h*.43f,78,h*.57f);p.setColor(0xee263d48);c.drawRoundRect(chatButton,0,18,18,p);Bitmap b=packs.ui("chat");if(b!=null)c.drawBitmap(b,null,new RectF(24,chatButton.top+12,66,chatButton.top+54),p);text(c,"چت",45,chatButton.bottom-12,10,Color.WHITE,Paint.Align.CENTER);}
    private void drawHint(Canvas c,int w,String value){p.setColor(0xee253943);RectF r=new RectF(w/2f-250,91,w/2f+250,143);c.drawRoundRect(r,17,17,p);text(c,value,w/2f,123,13,Color.WHITE,Paint.Align.CENTER);}
    private void drawToast(Canvas c,int w,int h){p.setColor(0xee101b21);RectF r=new RectF(w/2f-250,h*.80f-50,w/2f+250,h*.80f-8);c.drawRoundRect(r,15,15,p);text(c,toast,w/2f,r.centerY()+5,12,Color.WHITE,Paint.Align.CENTER);postInvalidateDelayed(250);}
    @Override public boolean onTouchEvent(MotionEvent e){scaleDetector.onTouchEvent(e);gestureDetector.onTouchEvent(e);return true;}
    private boolean handleTap(float x,float y){if(chatButton.contains(x,y)){listener.chat();return true;}for(int i=0;i<nav.length;i++)if(nav[i]!=null&&nav[i].contains(x,y)){switch(i){case 0:listener.attack();break;case 1:listener.shop();break;case 2:listener.army();break;case 3:listener.clan();break;case 4:listener.profile();break;}return true;}if(y<90||y>getHeight()*.82f)return false;int[]t=screen(x,y);if(t[0]<0||t[0]>=20||t[1]<0||t[1]>=20)return true;GameModel.Building hit=model.at(t[0],t[1]);if(buildMode!=null){if(hit!=null){showToast("این خانه اشغال است");return true;}listener.placeBuilding(buildMode,t[0],t[1]);buildMode=null;invalidate();return true;}selectedBuilding=hit;if(hit!=null){int cost=NativeBridge.upgradeCost(hit.id,hit.level);if(cost>=0){showToast("برای ارتقا دوباره روی ساختمان بزن");if(hit==selectedBuilding&&System.currentTimeMillis()-toastUntil+3200<900)listener.upgrade(hit);}}invalidate();return true;}
    private void drawBitmapBottom(Canvas c,Bitmap b,float cx,float bottom,float max){float scale=Math.min(max/Math.max(1,b.getWidth()),max/Math.max(1,b.getHeight()));float ww=b.getWidth()*scale,hh=b.getHeight()*scale;c.drawBitmap(b,null,new RectF(cx-ww/2,bottom-hh,cx+ww/2,bottom),p);}
    private void text(Canvas c,String s,float x,float y,float size,int color,Paint.Align a){p.setShader(null);p.setColor(color);p.setTextSize(size);p.setTextAlign(a);p.setTypeface(dry);c.drawText(s,x,y,p);}
}
