package ir.irautox.clashofdrayven;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.io.File;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity implements GameView.Listener {
    static { System.loadLibrary("clashofdrayven"); }
    public static native String nativeVersion();
    public static native int nativeGuard(int value);

    private final ExecutorService io=Executors.newSingleThreadExecutor();
    private final Handler main=new Handler(Looper.getMainLooper());
    private ApiClient api;private GameModel model;private GameView game;private File assets;private boolean savePending;
    private final Runnable production=new Runnable(){@Override public void run(){if(model!=null){int g=0,e=0;for(GameModel.Building b:model.buildings){if("goldmine".equals(b.id))g+=2+b.level*2;if("elixircollector".equals(b.id))e+=2+b.level*2;}if(g+e>0){model.gold=Math.min(9999999,model.gold+g);model.elixir=Math.min(9999999,model.elixir+e);dirty("Resources collected");game.invalidate();}}main.postDelayed(this,1800);}};

    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);getWindow().getDecorView().setSystemUiVisibility(5894);showLoading("Unpacking 20 protected asset packs...");io.execute(()->{try{assets=PackManager.prepare(this);api=new ApiClient(this);main.post(this::authenticate);}catch(Exception ex){main.post(()->fatal(ex));}});}
    private void showLoading(String s){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(Gravity.CENTER);l.setBackgroundColor(Color.rgb(17,31,39));TextView t=new TextView(this);t.setText("CLASH OF DRAYVEN\n\n"+s);t.setTextColor(Color.WHITE);t.setTextSize(22);t.setGravity(Gravity.CENTER);ProgressBar p=new ProgressBar(this);l.addView(t,new LinearLayout.LayoutParams(-1,-2));l.addView(p);setContentView(l);}
    private void authenticate(){if(api.token()==null){showAuth(false);return;}showLoading("Restoring your online village...");io.execute(()->{try{api.profile();GameModel m=api.state();main.post(()->launch(m));}catch(Exception ex){api.clear();main.post(()->showAuth(false));}});}

    private void showAuth(boolean register){final Dialog d=new Dialog(this);d.setTitle(register?"Create Drayven Account":"Login to Drayven");LinearLayout l=new LinearLayout(this);l.setPadding(34,24,34,24);l.setOrientation(LinearLayout.VERTICAL);l.setBackgroundColor(Color.rgb(27,43,52));TextView h=text(register?"CREATE ACCOUNT":"ENTER THE VILLAGE",24);l.addView(h);EditText user=input("Chief name / email",false);EditText email=input("Email",false);email.setVisibility(register?View.VISIBLE:View.GONE);EditText pass=input("Password",true);l.addView(user);l.addView(email);l.addView(pass);TextView status=text(register?"New chiefs receive 7,000 Gold, 7,000 Elixir and 250 Gems.":"Your village is restored from irautox.ir:8456",13);l.addView(status);Button go=new Button(this);go.setText(register?"CREATE & PLAY":"LOGIN & PLAY");l.addView(go);Button swap=new Button(this);swap.setText(register?"I ALREADY HAVE AN ACCOUNT":"CREATE NEW ACCOUNT");l.addView(swap);go.setOnClickListener(v->{go.setEnabled(false);status.setText("Connecting...");io.execute(()->{try{if(register)api.register(user.getText().toString().trim(),email.getText().toString().trim(),pass.getText().toString());else api.login(user.getText().toString().trim(),pass.getText().toString());GameModel m=api.state();main.post(()->{d.dismiss();launch(m);});}catch(Exception ex){main.post(()->{status.setText(ex.getMessage());go.setEnabled(true);});}});});swap.setOnClickListener(v->{d.dismiss();showAuth(!register);});d.setContentView(l);d.setCancelable(false);d.show();Window w=d.getWindow();if(w!=null)w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.48f),WindowManager.LayoutParams.WRAP_CONTENT);}
    private TextView text(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setTextSize(size);t.setPadding(8,10,8,10);return t;}
    private EditText input(String hint,boolean password){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(0xffaeb9bd);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setInputType(password?InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD:InputType.TYPE_CLASS_TEXT);e.setPadding(12,8,12,8);return e;}

    private void launch(GameModel m){model=m;game=new GameView(this,model,assets,this);setContentView(game);main.removeCallbacks(production);main.postDelayed(production,1800);Toast.makeText(this,nativeVersion()+" ready",Toast.LENGTH_SHORT).show();}

    @Override public void shop(){String[] items=new String[GameCatalog.BUILDINGS.length];for(int i=0;i<items.length;i++){GameCatalog.BuildingSpec s=GameCatalog.BUILDINGS[i];items[i]=s.name+"  •  "+s.cost+" "+s.currency;}new AlertDialog.Builder(this).setTitle("BUILD SHOP").setItems(items,(d,which)->game.selectBuilding(GameCatalog.BUILDINGS[which])).setNegativeButton("Close",null).show();}
    @Override public void army(){String[] items=new String[GameCatalog.UNITS.length];for(int i=0;i<items.length;i++){GameCatalog.UnitSpec u=GameCatalog.UNITS[i];items[i]=u.name+"  x"+model.units.getOrDefault(u.id,0)+"  •  "+u.cost+" "+u.currency;}new AlertDialog.Builder(this).setTitle("ARMY").setItems(items,(d,which)->recruit(GameCatalog.UNITS[which])).setNegativeButton("Close",null).show();}
    private void recruit(GameCatalog.UnitSpec u){boolean barracks=false;for(GameModel.Building b:model.buildings)if("barracks".equals(b.id))barracks=true;if(!barracks){game.showToast("Build a Barracks first");return;}if(!model.spend(u.currency,u.cost)){game.showToast("Not enough "+u.currency);return;}model.units.put(u.id,model.units.getOrDefault(u.id,0)+1);model.gainXp(4);dirty(u.name+" recruited");game.invalidate();}
    @Override public void attack(){int power=0,count=0;for(Map.Entry<String,Integer>e:model.units.entrySet()){GameCatalog.UnitSpec u=GameCatalog.unit(e.getKey());if(u!=null){power+=u.power*e.getValue();count+=e.getValue();}}if(count==0){game.showToast("Recruit troops before attacking");return;}final int pwr=power;new AlertDialog.Builder(this).setTitle("RIVAL STRONGHOLD FOUND").setMessage("Enemy defense: "+(700+model.level*95)+"\nYour army power: "+power+"\n\nStart the raid?").setPositiveButton("ATTACK",(d,w)->resolveRaid(pwr)).setNegativeButton("Cancel",null).show();}
    private void resolveRaid(int power){int defense=700+model.level*95;double ratio=Math.min(1.0,power/(double)Math.max(1,defense));int gold=(int)(900+ratio*5200);int elixir=(int)(700+ratio*4300);int lost=Math.max(1,(int)Math.round((1.0-ratio*.55)*.22*model.units.values().stream().mapToInt(Integer::intValue).sum()));for(String k:new ArrayList<>(model.units.keySet())){if(lost<=0)break;int n=model.units.get(k);int take=Math.min(n,Math.max(0,lost));model.units.put(k,n-take);lost-=take;}model.gold=Math.min(9999999,model.gold+gold);model.elixir=Math.min(9999999,model.elixir+elixir);model.gainXp((int)(40+ratio*110));dirty("Raid complete: +"+gold+" Gold, +"+elixir+" Elixir");game.invalidate();new AlertDialog.Builder(this).setTitle(ratio>.65?"VICTORY":"RAID COMPLETE").setMessage("Loot secured\nGold +"+gold+"\nElixir +"+elixir).setPositiveButton("Return",null).show();}
    @Override public void clan(){if(model.clanName!=null){new AlertDialog.Builder(this).setTitle(model.clanName+" ["+model.clanTag+"]").setMessage("Clan data is stored on the Drayven realm.").setPositiveButton("Close",null).show();return;}LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(28,10,28,10);EditText name=input("Clan name",false),tag=input("Tag",false);l.addView(name);l.addView(tag);new AlertDialog.Builder(this).setTitle("CREATE CLAN").setView(l).setPositiveButton("CREATE",(d,w)->io.execute(()->{try{JSONObject r=api.createClan(name.getText().toString().trim(),tag.getText().toString().trim().toUpperCase(Locale.ROOT));JSONObject c=r.getJSONObject("clan");model.clanName=c.optString("name");model.clanTag=c.optString("tag");main.post(()->{dirty("Clan created");game.invalidate();});}catch(Exception ex){main.post(()->game.showToast(ex.getMessage()));}})).setNegativeButton("Cancel",null).show();}
    @Override public void profile(){new AlertDialog.Builder(this).setTitle("CHIEF PROFILE").setMessage("Level "+model.level+"\nXP "+model.xp+"\n\nServer: "+ApiClient.BASE+"\nNative: "+nativeVersion()+"\nGuard: "+nativeGuard(model.level)).setPositiveButton("SYNC NOW",(d,w)->saveNow()).setNeutralButton("LOG OUT",(d,w)->{api.logout();recreate();}).setNegativeButton("Close",null).show();}
    @Override public void dirty(String toast){savePending=true;if(toast!=null&&game!=null)game.showToast(toast);main.removeCallbacks(saveDebounce);main.postDelayed(saveDebounce,1200);}
    private final Runnable saveDebounce=()->saveNow();
    private void saveNow(){if(!savePending||model==null||api==null)return;savePending=false;io.execute(()->{try{api.save(model);}catch(Exception ex){savePending=true;main.post(()->{if(game!=null)game.showToast("Sync failed: "+ex.getMessage());});}});}
    private void fatal(Exception ex){new AlertDialog.Builder(this).setTitle("Clash Of Drayven").setMessage("Startup failed:\n"+ex).setCancelable(false).setPositiveButton("Exit",(d,w)->finish()).show();}
    @Override protected void onPause(){saveNow();super.onPause();}
    @Override protected void onDestroy(){main.removeCallbacks(production);main.removeCallbacks(saveDebounce);io.shutdownNow();super.onDestroy();}
}
