package ir.irautox.clashofdrayven;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.graphics.Typeface;
import android.media.MediaPlayer;
import android.text.InputType;
import android.view.*;
import android.view.animation.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity implements GameView.Listener {
    private final ExecutorService io=Executors.newSingleThreadExecutor();private final Handler main=new Handler(Looper.getMainLooper());
    private ApiClient api;private GameModel model;private GameView game;private PackManager packs;private OfflineStore offline;private boolean savePending;private String playerName="فرمانده",activeMatchId=null;private JSONObject activeMatch=null;private Typeface vazir=Typeface.DEFAULT,magic=Typeface.DEFAULT_BOLD;private Dialog currentPanel;private TextView loadingStatus,loadingTip;private ProgressBar loadingBar;private int dots=0;
    private final Runnable dotsRun=new Runnable(){public void run(){if(loadingStatus!=null){dots=(dots+1)%4;StringBuilder s=new StringBuilder("در حال بارگذاری");for(int i=0;i<dots;i++)s.append('.');loadingStatus.setText(s.toString());main.postDelayed(this,420);}}};
    private final Runnable offlineProduction=new Runnable(){public void run(){if(model!=null&&!model.online){model.applyProduction();offline.save(model);if(game!=null)game.invalidate();}main.postDelayed(this,1800);}};
    private final Runnable onlineRefresh=new Runnable(){public void run(){if(model!=null&&model.online&&api!=null){io.execute(()->{try{GameModel fresh=api.state();main.post(()->{model=fresh;playerName=fresh.username;game=new GameView(MainActivity.this,model,packs,playerName,MainActivity.this);setContentView(game);});}catch(Exception ignored){}});}main.postDelayed(this,15000);}};

    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);getWindow().getDecorView().setSystemUiVisibility(5894);offline=new OfflineStore(this);try{vazir=Typeface.createFromAsset(getAssets(),"fonts/vazir.ttf");}catch(Exception ignored){}try{magic=Typeface.createFromAsset(getAssets(),"fonts/irautox_magic_5.ttf");}catch(Exception ignored){}showBrandSplash();main.postDelayed(this::showLoading,2200);}
    @Override protected void onDestroy(){main.removeCallbacksAndMessages(null);io.shutdownNow();if(currentPanel!=null)currentPanel.dismiss();super.onDestroy();}

    private void showBrandSplash(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.splash_irautox);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);root.addView(logo,new FrameLayout.LayoutParams((int)(getResources().getDisplayMetrics().widthPixels*.58f),(int)(getResources().getDisplayMetrics().heightPixels*.58f),Gravity.CENTER));AlphaAnimation pulse=new AlphaAnimation(1f,.2f);pulse.setDuration(620);pulse.setRepeatMode(Animation.REVERSE);pulse.setRepeatCount(Animation.INFINITE);logo.startAnimation(pulse);setContentView(root);try{MediaPlayer mp=MediaPlayer.create(this,R.raw.ding);if(mp!=null){mp.setOnCompletionListener(MediaPlayer::release);mp.start();}}catch(Exception ignored){}}
    private void showLoading(){FrameLayout root=new FrameLayout(this);ImageView bg=new ImageView(this);bg.setImageResource(R.drawable.loading_background);bg.setScaleType(ImageView.ScaleType.CENTER_CROP);root.addView(bg,new FrameLayout.LayoutParams(-1,-1));View shade=new View(this);shade.setBackgroundColor(0x66000000);root.addView(shade,new FrameLayout.LayoutParams(-1,-1));LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setPadding(dp(42),dp(24),dp(42),dp(24));loadingStatus=label("در حال بارگذاری",20,Color.WHITE,Gravity.CENTER);loadingTip=label(NativeBridge.loadingTip((int)(System.currentTimeMillis()/1000)),12,0xffe3edf0,Gravity.CENTER);loadingBar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);loadingBar.setMax(100);loadingBar.setProgress(3);TextView brand=titleLabel("CLASH OF DRAYVEN",30,0xffffd66b,Gravity.CENTER);box.addView(brand,lp(-1,-2,0,dp(20)));box.addView(loadingStatus,lp(-1,-2,0,dp(12)));box.addView(loadingBar,lp(Math.min(dp(650),(int)(getResources().getDisplayMetrics().widthPixels*.62f)),dp(16),0,dp(14)));box.addView(loadingTip,lp(-1,-2,0,0));FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL);bp.bottomMargin=dp(42);root.addView(box,bp);setContentView(root);main.removeCallbacks(dotsRun);main.post(dotsRun);bootstrap();}
    private void progress(int p,String stage){main.post(()->{if(loadingBar!=null)loadingBar.setProgress(Math.max(0,Math.min(100,p)));if(loadingTip!=null&&stage!=null)loadingTip.setText(stage+"\n"+NativeBridge.loadingTip(p+modelSeed()));});}
    private int modelSeed(){return(int)(System.currentTimeMillis()/1000L);}
    private void bootstrap(){io.execute(()->{try{progress(6,"راه‌اندازی LuaJIT و DrayvenEngine");if(!NativeBridge.luaReady())throw new IllegalStateException("LuaJIT core failed to initialize");packs=PackManager.prepare(this,(p,s)->progress(Math.min(90,p),s));progress(92,"بررسی اتصال امن");api=new ApiClient(this);boolean server=false;try{server=api.health().optBoolean("ok",false);}catch(Exception ignored){}progress(97,server?"سرور درایون پاسخ داد":"حالت آفلاین آماده است");Thread.sleep(350);progress(100,"قلمرو آماده است");final boolean online=server;main.postDelayed(()->afterLoad(online),450);}catch(Exception ex){main.post(()->fatal(ex));}});}
    private void afterLoad(boolean serverReachable){main.removeCallbacks(dotsRun);if(serverReachable&&api.hasSession()){io.execute(()->{try{JSONObject profile=api.profile();GameModel m=api.state();m.online=true;String n=userFrom(profile,m.username);m.username=n;main.post(()->launch(m));}catch(Exception ex){api.clear();main.post(this::showEntry);}});}else showEntry();}

    private void showEntry(){FrameLayout root=authBackground();LinearLayout card=card();card.setGravity(Gravity.CENTER_HORIZONTAL);card.addView(titleLabel("CLASH OF DRAYVEN",29,0xffffd26d,Gravity.CENTER),lp(-1,-2,0,dp(6)));card.addView(label("قلمروت را بساز، دفاع کن و حمله برو",12,0xffa9c5cc,Gravity.CENTER),lp(-1,-2,0,dp(24)));Button login=gameButton("ورود به حساب",0xffd18431),register=gameButton("شروع فرمانده جدید",0xff3a985e),guest=gameButton("بازی آفلاین",0xff3a505b);card.addView(login,lp(-1,dp(54),0,dp(10)));card.addView(register,lp(-1,dp(54),0,dp(10)));card.addView(guest,lp(-1,dp(50),0,0));login.setOnClickListener(v->showAuth(false));register.setOnClickListener(v->showAuth(true));guest.setOnClickListener(v->{GameModel m=offline.load();if(m==null)m=GameModel.freshOffline();m.online=false;m.username="فرمانده آفلاین";launch(m);});FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(Math.min(dp(470),(int)(getResources().getDisplayMetrics().widthPixels*.48f)),-2,Gravity.RIGHT|Gravity.CENTER_VERTICAL);cp.rightMargin=dp(55);root.addView(card,cp);setContentView(root);}
    private void showAuth(boolean register){FrameLayout root=authBackground();LinearLayout card=card();card.addView(titleLabel(register?"ساخت حساب":"خوش برگشتی",26,0xffffd26d,Gravity.CENTER),lp(-1,-2,0,dp(18)));EditText user=field(register?"نام فرمانده":"نام فرمانده یا ایمیل",false),email=field("ایمیل",false),pass=field("رمز عبور",true),otp=field("کد ۶ رقمی (اگر فعال است)",false);otp.setInputType(InputType.TYPE_CLASS_NUMBER);if(register){card.addView(user,lp(-1,dp(50),0,dp(8)));card.addView(email,lp(-1,dp(50),0,dp(8)));card.addView(pass,lp(-1,dp(50),0,dp(12)));}else{card.addView(user,lp(-1,dp(50),0,dp(8)));card.addView(pass,lp(-1,dp(50),0,dp(8)));card.addView(otp,lp(-1,dp(50),0,dp(12)));}TextView status=label(register?"نام فرمانده ۳ تا ۲۰ کاراکتر":"ورود امن به قلمرو",11,0xffa7bec5,Gravity.CENTER);Button go=gameButton(register?"ساخت حساب و شروع":"ورود",0xffd18431),back=gameButton("بازگشت",0xff344b55);card.addView(status,lp(-1,-2,0,dp(10)));card.addView(go,lp(-1,dp(52),0,dp(8)));card.addView(back,lp(-1,dp(46),0,0));back.setOnClickListener(v->showEntry());go.setOnClickListener(v->{String u=user.getText().toString().trim(),pw=pass.getText().toString();if(u.isEmpty()||pw.length()<8||(register&&email.getText().toString().trim().isEmpty())){status.setText("اطلاعات لازم را کامل کن");return;}go.setEnabled(false);status.setText("در حال اتصال امن...");io.execute(()->{try{JSONObject auth=register?api.register(u,email.getText().toString().trim(),pw):api.login(u,pw,otp.getText().toString());GameModel m=GameModel.from(auth);try{m=api.state();}catch(Exception ignored){}m.online=true;m.username=userFrom(auth,u);GameModel finalM=m;main.post(()->launch(finalM));}catch(Exception ex){main.post(()->{status.setText(ex.getMessage());go.setEnabled(true);});}});});FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(Math.min(dp(500),(int)(getResources().getDisplayMetrics().widthPixels*.50f)),-2,Gravity.RIGHT|Gravity.CENTER_VERTICAL);cp.rightMargin=dp(50);root.addView(card,cp);setContentView(root);}
    private FrameLayout authBackground(){FrameLayout root=new FrameLayout(this);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);ImageView bg=new ImageView(this);bg.setImageResource(R.drawable.loading_background);bg.setScaleType(ImageView.ScaleType.CENTER_CROP);root.addView(bg,new FrameLayout.LayoutParams(-1,-1));View shade=new View(this);shade.setBackgroundColor(0x44000000);root.addView(shade,new FrameLayout.LayoutParams(-1,-1));return root;}
    private String userFrom(JSONObject root,String fallback){JSONObject u=root==null?null:root.optJSONObject("user");String n=u==null?null:u.optString("username",null);return n==null||n.trim().isEmpty()?fallback:n.trim();}

    private void launch(GameModel m){model=m;playerName=m.username==null?playerName:m.username;game=new GameView(this,model,packs,playerName,this);setContentView(game);main.removeCallbacks(offlineProduction);main.removeCallbacks(onlineRefresh);if(model.online)main.postDelayed(onlineRefresh,15000);else main.postDelayed(offlineProduction,1800);if(!model.tutorialDone)main.postDelayed(()->showTutorial(0),500);}
    private void showTutorial(int step){String[]texts={"به قلمرو درایون خوش آمدی! با دو انگشت روی دهکده زوم کن و محیط را ببین.","از فروشگاه یک ساختمان انتخاب کن و روی خانه خالی قرار بده.","سربازخانه، نیرو و دفاع‌ها پایه حمله و دفاع تو هستند. جم را برای قهرمان‌ها و خریدهای ویژه نگه دار.","چت سمت چپ را باز کن؛ در حالت آنلاین چت جهانی و کلن در دسترس است. آموزش تمام شد؛ هدیه شروع منتظر توست."};if(step>=texts.length){completeTutorial();return;}final Dialog d=panelDialog("آموزش فرمانده");LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);ImageView guide=new ImageView(this);Bitmap bmp=packs.brand("duf");if(bmp!=null)guide.setImageBitmap(bmp);guide.setScaleType(ImageView.ScaleType.CENTER_INSIDE);row.addView(guide,new LinearLayout.LayoutParams(0,dp(245),.45f));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setPadding(dp(22),dp(12),dp(22),dp(12));TextView t=label(texts[step],15,Color.WHITE,Gravity.RIGHT);Button next=gameButton(step==texts.length-1?"دریافت هدیه شروع":"ادامه",0xffd18431);info.addView(t,lp(-1,-2,0,dp(22)));info.addView(next,lp(-1,dp(52),0,0));row.addView(info,new LinearLayout.LayoutParams(0,-2,.55f));panelBody(d).addView(row);next.setOnClickListener(v->{d.dismiss();showTutorial(step+1);});d.show();}
    private void completeTutorial(){if(model.tutorialDone)return;model.tutorialDone=true;if(model.online){io.execute(()->{try{JSONObject r=api.tutorialComplete();GameModel m=GameModel.from(r);m.online=true;main.post(()->{model=m;launch(model);});}catch(Exception ex){main.post(()->game.showToast("آموزش تمام شد؛ هدیه پس از اتصال دریافت می‌شود"));}});}else{if(!model.starterGiftClaimed){model.gold+=3000;model.elixir+=3000;model.gems+=25;model.starterGiftClaimed=true;}offline.save(model);game.showToast("هدیه شروع: ۳۰۰۰ طلا • ۳۰۰۰ اکسیر • ۲۵ جم");game.invalidate();}}

    @Override public void placeBuilding(GameCatalog.BuildingSpec s,int x,int y){if(model.at(x,y)!=null)return;if(model.online){int oldG=model.gold,oldE=model.elixir,oldM=model.gems;if(!model.spend(s.currency,s.cost)){game.showToast("منابع کافی نیست");return;}GameModel.Building b=new GameModel.Building(UUID.randomUUID().toString(),s.id,x,y,1);model.buildings.add(b);savePending=true;game.invalidate();io.execute(()->{try{JSONObject r=api.syncLayout(model);GameModel fresh=GameModel.from(r);fresh.online=true;main.post(()->{model=fresh;launch(model);});}catch(Exception ex){main.post(()->{model.buildings.remove(b);model.gold=oldG;model.elixir=oldE;model.gems=oldM;game.showToast("ساخت توسط سرور تایید نشد");game.invalidate();});}});}else{if(!model.spend(s.currency,s.cost)){game.showToast("منابع کافی نیست");return;}model.buildings.add(new GameModel.Building(UUID.randomUUID().toString(),s.id,x,y,1));model.gainXp(18);offline.save(model);game.showToast("ساختمان ساخته شد");game.invalidate();}}
    @Override public void upgrade(GameModel.Building b){int cost=NativeBridge.upgradeCost(b.id,b.level);if(cost<0){game.showToast("این ساختمان در حداکثر سطح است");return;}if(model.online){io.execute(()->{try{JSONObject r=api.upgrade(b.instance);GameModel fresh=GameModel.from(r);fresh.online=true;main.post(()->{model=fresh;launch(model);game.showToast("ارتقا انجام شد");});}catch(Exception ex){main.post(()->game.showToast(ex.getMessage()));}});}else{if(!model.spend("gold",cost)){game.showToast("طلای کافی نیست");return;}b.level++;if("townhall".equals(b.id))model.townHallLevel=b.level;model.gainXp(12+b.level*3);offline.save(model);game.showToast("ارتقا به سطح "+b.level);game.invalidate();}}
    @Override public void shop(){Dialog d=panelDialog("فروشگاه درایون");LinearLayout body=panelBody(d);TextView gems=label("جم: "+model.gems+" • برای قهرمان‌ها و کالاهای ویژه",12,0xff50e0ae,Gravity.RIGHT);body.addView(gems,lp(-1,-2,0,dp(12)));for(GameCatalog.BuildingSpec s:GameCatalog.BUILDINGS){Button b=gameButton(s.name+"    "+s.cost+" "+GameCatalog.currencyName(s.currency),0xff344d58);body.addView(b,lp(-1,dp(48),0,dp(6)));b.setOnClickListener(v->{d.dismiss();game.selectBuilding(s);});}Button hero=gameButton("قهرمان نگهبان • ۱۵۰ جم",0xff694f91);body.addView(hero,lp(-1,dp(50),0,0));hero.setOnClickListener(v->{if(!model.online){game.showToast("خرید قهرمان به حساب آنلاین نیاز دارد");d.dismiss();return;}io.execute(()->{try{JSONObject r=api.buy("hero_guardian");GameModel fresh=GameModel.from(r);fresh.online=true;main.post(()->{d.dismiss();model=fresh;launch(model);});}catch(Exception ex){main.post(()->toast(ex.getMessage()));}});});d.show();}
    @Override public void army(){Dialog d=panelDialog("ارتش");LinearLayout body=panelBody(d);for(GameCatalog.UnitSpec u:GameCatalog.UNITS){int have=model.units.getOrDefault(u.id,0);Button b=gameButton(u.name+"   ×"+have+"   • "+u.cost+" "+GameCatalog.currencyName(u.currency),0xff344d58);body.addView(b,lp(-1,dp(50),0,dp(7)));b.setOnClickListener(v->{if(model.online){io.execute(()->{try{JSONObject r=api.train(u.id,1);GameModel fresh=GameModel.from(r);fresh.online=true;main.post(()->{d.dismiss();model=fresh;launch(model);});}catch(Exception ex){main.post(()->toast(ex.getMessage()));}});}else{boolean barracks=false;for(GameModel.Building x:model.buildings)if("barracks".equals(x.id))barracks=true;if(!barracks){toast("اول سربازخانه بساز");return;}if(!model.spend(u.currency,u.cost)){toast("منابع کافی نیست");return;}model.units.put(u.id,have+1);model.gainXp(4);offline.save(model);d.dismiss();game.invalidate();}});}d.show();}
    @Override public void clan(){Dialog d=panelDialog(model.clanName==null?"کلن":"کلن • "+model.clanName);LinearLayout body=panelBody(d);if(model.clanName!=null){body.addView(label("["+model.clanTag+"]\nفرمانده کلن و چت کلن از پنل چت در دسترس است.",14,Color.WHITE,Gravity.RIGHT));Button chat=gameButton("باز کردن چت کلن",0xff3a7a96);body.addView(chat,lp(-1,dp(50),dp(14),0));chat.setOnClickListener(v->{d.dismiss();showChat("clan");});}else if(!model.online){body.addView(label("ساخت کلن به اتصال آنلاین نیاز دارد.",14,Color.WHITE,Gravity.CENTER));}else{EditText name=field("نام کلن",false),tag=field("تگ کلن",false);body.addView(name,lp(-1,dp(48),0,dp(8)));body.addView(tag,lp(-1,dp(48),0,dp(8)));Button create=gameButton("ساخت کلن",0xffd18431);body.addView(create,lp(-1,dp(50),0,0));create.setOnClickListener(v->io.execute(()->{try{JSONObject r=api.createClan(name.getText().toString().trim(),tag.getText().toString().trim().toUpperCase(Locale.ROOT));GameModel fresh=api.state();fresh.online=true;main.post(()->{d.dismiss();model=fresh;launch(model);});}catch(Exception ex){main.post(()->toast(ex.getMessage()));}}));}d.show();}
    @Override public void chat(){showChat("global");}
    private void showChat(String initial){Dialog d=panelDialog("چت");LinearLayout body=panelBody(d);LinearLayout tabs=new LinearLayout(this);tabs.setOrientation(LinearLayout.HORIZONTAL);Button global=gameButton("جهانی",0xff3a7a96),clan=gameButton("کلن",0xff3a505b);tabs.addView(global,new LinearLayout.LayoutParams(0,dp(46),1));tabs.addView(clan,new LinearLayout.LayoutParams(0,dp(46),1));body.addView(tabs,lp(-1,-2,0,dp(8)));ScrollView scroll=new ScrollView(this);LinearLayout msgs=new LinearLayout(this);msgs.setOrientation(LinearLayout.VERTICAL);scroll.addView(msgs);body.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout sendRow=new LinearLayout(this);sendRow.setOrientation(LinearLayout.HORIZONTAL);EditText input=field("پیام...",false);Button send=gameButton("ارسال",0xffd18431);sendRow.addView(input,new LinearLayout.LayoutParams(0,dp(48),1));sendRow.addView(send,new LinearLayout.LayoutParams(dp(110),dp(48)));body.addView(sendRow,lp(-1,-2,dp(8),0));final String[]scope={initial};Runnable load=()->loadChat(scope[0],msgs);global.setOnClickListener(v->{scope[0]="global";load.run();});clan.setOnClickListener(v->{scope[0]="clan";load.run();});send.setOnClickListener(v->{String raw=input.getText().toString().trim();if(raw.isEmpty())return;if(ProfanityFilter.containsBlocked(raw)){input.setText(ProfanityFilter.clean(raw));toast("بخش نامناسب پیام حذف شد");return;}if(!model.online){toast("چت فقط در حالت آنلاین فعال است");return;}io.execute(()->{try{api.sendChat(scope[0],raw);main.post(()->{input.setText("");load.run();});}catch(Exception ex){main.post(()->toast(ex.getMessage()));}});});d.setOnShowListener(x->load.run());d.show();}
    private void loadChat(String scope,LinearLayout msgs){msgs.removeAllViews();if(!model.online){msgs.addView(label("برای چت وارد حساب آنلاین شو.",13,0xffc7d3d7,Gravity.CENTER));return;}io.execute(()->{try{JSONObject r=api.chat(scope,0);JSONArray a=r.optJSONArray("messages");ArrayList<String>lines=new ArrayList<>();if(a!=null)for(int i=0;i<a.length();i++){JSONObject m=a.getJSONObject(i);lines.add(m.optString("username","?")+"  L"+m.optInt("level",1)+"  #"+m.optInt("playerId",0)+"\n"+ProfanityFilter.clean(m.optString("message","")));}main.post(()->{msgs.removeAllViews();for(String line:lines){TextView t=label(line,12,Color.WHITE,Gravity.RIGHT);t.setPadding(dp(12),dp(7),dp(12),dp(7));t.setBackground(round(0xff263943,dp(12),0));msgs.addView(t,lp(-1,-2,0,dp(5)));}});}catch(Exception ex){main.post(()->{msgs.removeAllViews();msgs.addView(label(ex.getMessage(),12,0xffffa29c,Gravity.CENTER));});}});}
    @Override public void profile(){Dialog d=panelDialog("پروفایل فرمانده");LinearLayout body=panelBody(d);String info=playerName+"\n#"+(model.playerId>0?model.playerId:"OFFLINE")+"\n\nسطح "+model.level+"   •   تالار "+model.townHallLevel+"\n"+model.rank()+"   •   "+model.points+" امتیاز\n\nافتخارات\n★ فرمانده قلمرو\n★ "+(model.tutorialDone?"آموزش کامل":"تازه‌وارد")+"\n★ "+(model.clanName==null?"بدون کلن":"عضو "+model.clanName)+"\n\nسازندگان: IrAutoX / DeathAmir\nDrayvenEngine: "+NativeBridge.version()+"\n"+NativeBridge.luaVersion();body.addView(label(info,14,Color.WHITE,Gravity.RIGHT),lp(-1,-2,0,dp(14)));Button settings=gameButton("تنظیمات حساب و امنیت",0xff3a7a96);body.addView(settings,lp(-1,dp(50),0,0));settings.setOnClickListener(v->{d.dismiss();settings();});d.show();}
    private void settings(){Dialog d=panelDialog("تنظیمات و امنیت");LinearLayout body=panelBody(d);body.addView(label("حساب خود را لینک کن و تایید دو مرحله‌ای TOTP را فعال کن.",12,0xffc6d5d9,Gravity.RIGHT),lp(-1,-2,0,dp(12)));Button link=gameButton("لینک / بروزرسانی حساب",0xff3a7a96),totp=gameButton("فعال‌سازی تایید دو مرحله‌ای",0xff54865a),logout=gameButton("خروج از حساب",0xff934b4b);body.addView(link,lp(-1,dp(50),0,dp(8)));body.addView(totp,lp(-1,dp(50),0,dp(8)));body.addView(logout,lp(-1,dp(50),0,0));link.setOnClickListener(v->accountLink(d));totp.setOnClickListener(v->totpSetup(d));logout.setOnClickListener(v->{if(api!=null)api.logout();d.dismiss();showEntry();});d.show();}
    private void accountLink(Dialog parent){if(!model.online){toast("به حساب آنلاین نیاز دارد");return;}Dialog d=panelDialog("لینک حساب");LinearLayout b=panelBody(d);EditText email=field("ایمیل",false),pass=field("رمز عبور",true);b.addView(email,lp(-1,dp(48),0,dp(8)));b.addView(pass,lp(-1,dp(48),0,dp(8)));Button go=gameButton("ذخیره امن",0xffd18431);b.addView(go,lp(-1,dp(50),0,0));go.setOnClickListener(v->io.execute(()->{try{api.linkAccount(email.getText().toString().trim(),pass.getText().toString());main.post(()->{d.dismiss();toast("حساب لینک شد");});}catch(Exception ex){main.post(()->toast(ex.getMessage()));}}));d.show();}
    private void totpSetup(Dialog parent){if(!model.online){toast("به حساب آنلاین نیاز دارد");return;}io.execute(()->{try{JSONObject begin=api.beginTotp();String secret=begin.optString("secret");main.post(()->{Dialog d=panelDialog("TOTP دو مرحله‌ای");LinearLayout b=panelBody(d);b.addView(label("این کلید را در Google Authenticator / Aegis اضافه کن:\n"+secret,12,Color.WHITE,Gravity.CENTER),lp(-1,-2,0,dp(12)));EditText otp=field("کد ۶ رقمی",false);otp.setInputType(InputType.TYPE_CLASS_NUMBER);b.addView(otp,lp(-1,dp(48),0,dp(8)));Button go=gameButton("تایید و فعال‌سازی",0xff54865a);b.addView(go,lp(-1,dp(50),0,0));go.setOnClickListener(v->io.execute(()->{try{api.confirmTotp(otp.getText().toString());main.post(()->{d.dismiss();toast("تایید دو مرحله‌ای فعال شد");});}catch(Exception ex){main.post(()->toast(ex.getMessage()));}}));d.show();});}catch(Exception ex){main.post(()->toast(ex.getMessage()));}});}
    @Override public void attack(){int count=0;for(int n:model.units.values())count+=n;if(count<=0){game.showToast("قبل از حمله نیرو آموزش بده");return;}if(!model.online){activeMatchId=null;activeMatch=null;startBattle(null);return;}game.showToast("در حال جست‌وجوی حریف واقعی...");io.execute(()->{try{JSONObject r=api.matchmake();activeMatchId=r.optString("matchId",null);activeMatch=r;main.post(()->startBattle(r));}catch(Exception ex){main.post(()->game.showToast("حریف آنلاین پیدا نشد: "+ex.getMessage()));}});}
    private void startBattle(JSONObject match){main.removeCallbacks(offlineProduction);main.removeCallbacks(onlineRefresh);BattleView battle=new BattleView(this,model,packs,playerName,match,(gold,elixir,stars,destruction)->finishBattle(gold,elixir,stars,destruction));setContentView(battle);}
    private void finishBattle(int localGold,int localElixir,int stars,int destruction){if(model.online&&activeMatchId!=null){io.execute(()->{try{JSONObject r=api.finishBattle(activeMatchId,destruction,stars);GameModel fresh=GameModel.from(r);fresh.online=true;main.post(()->{activeMatchId=null;activeMatch=null;model=fresh;launch(model);game.showToast("نتیجه توسط سرور تایید شد");});}catch(Exception ex){main.post(()->{launch(model);game.showToast("نتیجه هنوز تایید نشده: "+ex.getMessage());});}});}else{model.gold=Math.min(9_999_999,model.gold+localGold);model.elixir=Math.min(9_999_999,model.elixir+localElixir);model.gainXp(20+destruction+stars*20);model.points=Math.max(0,model.points+(stars*24+destruction/5-15));offline.save(model);launch(model);}}
    @Override public void dirty(String toast){savePending=true;if(toast!=null&&game!=null)game.showToast(toast);if(!model.online)offline.save(model);}

    private Dialog panelDialog(String title){Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setPadding(dp(18),dp(14),dp(18),dp(18));shell.setBackground(round(0xfa182830,dp(24),0x55ffffff));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView t=titleLabel(title,20,0xffffd06b,Gravity.RIGHT);Button close=gameButton("×",0xff874444);head.addView(t,new LinearLayout.LayoutParams(0,dp(48),1));head.addView(close,new LinearLayout.LayoutParams(dp(58),dp(48)));shell.addView(head);ScrollView scroll=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setId(0x147711);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(8),dp(10),dp(8),dp(6));scroll.addView(body);shell.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));d.setContentView(shell);Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.74f),(int)(getResources().getDisplayMetrics().heightPixels*.84f));w.setGravity(Gravity.CENTER);}close.setOnClickListener(v->d.dismiss());currentPanel=d;return d;}
    private LinearLayout panelBody(Dialog d){return d.findViewById(0x147711);}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(30),dp(26),dp(30),dp(26));c.setBackground(round(0xf11b2d36,dp(26),0x33ffffff));return c;}
    private EditText field(String hint,boolean password){EditText e=new EditText(this);e.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setTypeface(vazir);e.setHint(hint);e.setHintTextColor(0xff829ba3);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setTextSize(13);e.setPadding(dp(16),0,dp(16),0);e.setBackground(round(0xff10222a,dp(13),0x554d7580));e.setInputType(password?InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD:InputType.TYPE_CLASS_TEXT);return e;}
    private Button gameButton(String text,int color){Button b=new Button(this);b.setTypeface(vazir);b.setText(text);b.setTextColor(Color.WHITE);b.setTextSize(12);b.setAllCaps(false);b.setBackground(round(color,dp(14),0x33ffffff));return b;}
    private TextView label(String text,int size,int color,int gravity){TextView t=new TextView(this);t.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);t.setTextDirection(View.TEXT_DIRECTION_RTL);t.setTypeface(vazir);t.setText(text);t.setTextColor(color);t.setTextSize(size);t.setGravity(gravity);return t;}
    private TextView titleLabel(String text,int size,int color,int gravity){TextView t=label(text,size,color,gravity);t.setTypeface(magic);return t;}
    private GradientDrawable round(int fill,float radius,int stroke){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(radius);if(stroke!=0)d.setStroke(dp(1),stroke);return d;}
    private LinearLayout.LayoutParams lp(int w,int h,int top,int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.topMargin=top;p.bottomMargin=bottom;return p;}
    private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private void fatal(Exception ex){FrameLayout r=authBackground();LinearLayout c=card();c.addView(titleLabel("Clash Of Drayven",24,0xffffd06b,Gravity.CENTER),lp(-1,-2,0,dp(12)));c.addView(label("راه‌اندازی ناموفق بود:\n"+ex.getMessage(),13,Color.WHITE,Gravity.CENTER),lp(-1,-2,0,dp(16)));Button retry=gameButton("تلاش دوباره",0xffd18431);c.addView(retry,lp(-1,dp(52),0,0));retry.setOnClickListener(v->recreate());r.addView(c,new FrameLayout.LayoutParams(Math.min(dp(550),(int)(getResources().getDisplayMetrics().widthPixels*.60f)),-2,Gravity.CENTER));setContentView(r);}
}
