<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ClashOfDrayven</AssemblyName>
    <RootNamespace>ClashOfDrayven</RootNamespace>
    <StartupObject>ClashOfDrayven.OnlineProgram</StartupObject>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Security" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
